Repository billbill-project/bill-api-server, pull requests merged in 2024-11, with the labels that each got.

#11 중간 브랜치 동기화
  build.gradle
  src/main/java/site/billbill/apiserver/api/auth/controller/AuthController.java
  src/main/java/site/billbill/apiserver/api/auth/domain/UserBaseInfo.java
  src/main/java/site/billbill/apiserver/api/auth/dto/request/AgreeRequest.java
  src/main/java/site/billbill/apiserver/api/auth/dto/request/LocationRequest.java
  src/main/java/site/billbill/apiserver/api/auth/dto/request/LoginRequest.java
  src/main/java/site/billbill/apiserver/api/auth/dto/request/ReissueRequest.java
  src/main/java/site/billbill/apiserver/api/auth/dto/request/SignupRequest.java
  src/main/java/site/billbill/apiserver/api/auth/service/AuthService.java
  src/main/java/site/billbill/apiserver/api/auth/service/AuthServiceImpl.java
  src/main/java/site/billbill/apiserver/common/enums/exception/ErrorCode.java
  src/main/java/site/billbill/apiserver/common/utils/jwt/JWTUtil.java
  src/main/java/site/billbill/apiserver/config/WebMvcConfig.java
  src/main/java/site/billbill/apiserver/config/interceptor/BillApiInterceptor.java
  src/main/java/site/billbill/apiserver/config/security/SecurityConfig.java
  src/main/java/site/billbill/apiserver/model/user/UserJpaEntity.java
  src/main/java/site/billbill/apiserver/model/user/UserLocationJpaEntity.java
  src/main/java/site/billbill/apiserver/repository/user/UserIdentityRepository.java
  src/main/java/site/billbill/apiserver/repository/user/UserLocationReposity.java
Labels: :+1: feat

#13 Feature/auth
  src/main/java/site/billbill/apiserver/api/auth/controller/AuthController.java
  src/main/java/site/billbill/apiserver/api/auth/dto/request/AgreeRequest.java
  src/main/java/site/billbill/apiserver/api/auth/dto/request/DeviceRequest.java
  src/main/java/site/billbill/apiserver/api/auth/dto/request/SignupRequest.java
  src/main/java/site/billbill/apiserver/api/auth/service/AuthServiceImpl.java
  src/main/java/site/billbill/apiserver/common/enums/user/DeviceType.java
  src/main/java/site/billbill/apiserver/common/utils/jwt/JWTUtil.java
  src/main/java/site/billbill/apiserver/model/user/UserAgreeHistJpaEntity.java
  src/main/java/site/billbill/apiserver/model/user/UserDeviceJpaEntity.java
  src/main/java/site/billbill/apiserver/model/user/UserJpaEntity.java
  src/main/java/site/billbill/apiserver/repository/user/UserAgreeHistRepository.java
  src/main/java/site/billbill/apiserver/repository/user/UserDeviceRepository.java
Labels: :+1: feat

#14 fix: swagger 경로 interceptor 제외
  src/main/java/site/billbill/apiserver/config/WebMvcConfig.java
Labels: :-1: fix

#15 fix: addResourceHandler 추가
  src/main/java/site/billbill/apiserver/config/WebMvcConfig.java
Labels: :-1: fix

#18 [fix] 개발서버 ip 변경
  src/main/java/site/billbill/apiserver/BillApiServerApplication.java
Labels: :hammer: ci/cd, :-1: fix

#20 [fix] 개발서버 ip 변경
  .github/workflows/dev_deply.yml
Labels: :hammer: ci/cd, :-1: fix

#21 [fix] 개발서버 ip 변경
  .github/workflows/dev_deply.yml
Labels: :hammer: ci/cd, :-1: fix

#23 [fix] 개발서버 ip 변경
  .github/workflows/dev_deply.yml
Labels: :hammer: ci/cd, :-1: fix

#24 [fix] yml문 변경
  .github/workflows/dev_deply.yml
Labels: :-1: fix

#26 [fix]workflows 수정
  .github/workflows/dev_deply.yml
Labels: :hammer: ci/cd, :-1: fix

#30 [fix]workflows 수정
  .github/workflows/dev_deply.yml
Labels: :hammer: ci/cd, :-1: fix

#32 Feature/auth
  src/main/java/site/billbill/apiserver/api/auth/service/AuthServiceImpl.java
  src/main/java/site/billbill/apiserver/common/utils/jwt/JWTUtil.java
  src/main/java/site/billbill/apiserver/model/user/UserJpaEntity.java
  src/main/java/site/billbill/apiserver/repository/user/UserIdentityDslRepository.java
  src/main/java/site/billbill/apiserver/repository/user/UserIdentityDslRepositoryImpl.java
  src/main/java/site/billbill/apiserver/repository/user/UserIdentityRepository.java
  src/main/java/site/billbill/apiserver/repository/user/UserRepository.java
Labels: :+1: feat

#51 fix: token 발급 만료 수정
  src/main/java/site/billbill/apiserver/api/auth/service/AuthServiceImpl.java
  src/main/java/site/billbill/apiserver/common/utils/jwt/JWTUtil.java
  src/main/java/site/billbill/apiserver/model/user/UserJpaEntity.java
Labels: :-1: fix

#52 Feature/image upload
  .github/workflows/dev_deply.yml
  build.gradle
  src/main/java/site/billbill/apiserver/api/s3/Service/S3Service.java
  src/main/java/site/billbill/apiserver/api/s3/Service/S3ServiceImpl.java
  src/main/java/site/billbill/apiserver/api/s3/controller/S3Controller.java
  src/main/java/site/billbill/apiserver/api/s3/converter/S3Converter.java
  src/main/java/site/billbill/apiserver/api/s3/dto/request/S3Request.java
  src/main/java/site/billbill/apiserver/api/s3/dto/response/S3Response.java
  src/main/java/site/billbill/apiserver/config/WebMvcConfig.java
  src/main/java/site/billbill/apiserver/config/s3/S3Config.java
  src/main/java/site/billbill/apiserver/config/security/SecurityConfig.java
Labels: :hammer: ci/cd, :+1: feat

#54 [feat] s3 최종구현
  src/main/java/site/billbill/apiserver/api/s3/controller/S3Controller.java
Labels: :hammer: ci/cd, :+1: feat

#56 fix: PR용 임시 커밋
  src/main/java/site/billbill/apiserver/repository/user/UserDslRepositoryImpl.java
Labels: :hammer: ci/cd

#57 [fix] deploy 수정
  .github/workflows/dev_deply.yml
  src/main/java/site/billbill/apiserver/repository/user/UserDslRepositoryImpl.java
Labels: :-1: fix

#59 [feat] 대여 게시물 생성
  src/main/java/site/billbill/apiserver/api/borrowPosts/dto/request/PostsRequest.java
Labels: :hammer: ci/cd, :+1: feat

#60 [fix] swagger 수정
  src/main/java/site/billbill/apiserver/api/borrowPosts/dto/request/PostsRequest.java
Labels: :hammer: ci/cd, :+1: feat

#61 Feature/borrow posts
  src/main/java/site/billbill/apiserver/api/borrowPosts/controller/PostsController.java
  src/main/java/site/billbill/apiserver/api/borrowPosts/converter/PostsConverter.java
  src/main/java/site/billbill/apiserver/api/borrowPosts/dto/response/PostsResponse.java
  src/main/java/site/billbill/apiserver/api/borrowPosts/service/PostsService.java
  src/main/java/site/billbill/apiserver/api/borrowPosts/service/PostsServiceImpl.java
  src/main/java/site/billbill/apiserver/model/post/ItemsCategoryJpaEntity.java
  src/main/java/site/billbill/apiserver/model/post/ItemsJpaEntity.java
  src/main/java/site/billbill/apiserver/repository/borrowPosts/ItemDslRepository.java
  src/main/java/site/billbill/apiserver/repository/borrowPosts/ItemDslRepositoryImpl.java
  src/main/java/site/billbill/apiserver/repository/borrowPosts/ItemsCategoryRepository.java
  src/main/java/site/billbill/apiserver/repository/borrowPosts/ItemsRepository.java
Labels: :hammer: ci/cd

#62 Feature/borrow posts
  src/main/java/site/billbill/apiserver/api/borrowPosts/controller/PostsController.java
  src/main/java/site/billbill/apiserver/api/borrowPosts/converter/PostsConverter.java
  src/main/java/site/billbill/apiserver/api/borrowPosts/dto/request/PostsRequest.java
  src/main/java/site/billbill/apiserver/api/borrowPosts/dto/response/PostsResponse.java
  src/main/java/site/billbill/apiserver/api/borrowPosts/service/PostsService.java
  src/main/java/site/billbill/apiserver/api/borrowPosts/service/PostsServiceImpl.java
  src/main/java/site/billbill/apiserver/repository/borrowPosts/ItemsBorrowStatusRepository.java
Labels: :hammer: ci/cd, :+1: feat

#63 [feat] 게시물 상세 조회
  src/main/java/site/billbill/apiserver/api/borrowPosts/service/PostsServiceImpl.java
Labels: :hammer: ci/cd, :+1: feat

#64 Feature/users API 개발 및 중간 model 공유
  src/main/java/site/billbill/apiserver/api/users/controller/UserController.java
  src/main/java/site/billbill/apiserver/api/users/dto/response/BorrowHistoryResponse.java
  src/main/java/site/billbill/apiserver/api/users/dto/response/PostHistoryResponse.java
  src/main/java/site/billbill/apiserver/api/users/service/UserService.java
  src/main/java/site/billbill/apiserver/api/users/service/UserServiceImpl.java
  src/main/java/site/billbill/apiserver/common/utils/PortOneUtil.java
  src/main/java/site/billbill/apiserver/common/utils/jwt/JWTUtil.java
  src/main/java/site/billbill/apiserver/common/utils/posts/ItemHistoryType.java
  src/main/java/site/billbill/apiserver/common/utils/posts/ItemType.java
  src/main/java/site/billbill/apiserver/model/chat/ChatChannelJpaEntity.java
  src/main/java/site/billbill/apiserver/model/post/BorrowHistJapEntity.java
  src/main/java/site/billbill/apiserver/repository/borrowPosts/ItemDslRepository.java
  src/main/java/site/billbill/apiserver/repository/borrowPosts/ItemDslRepositoryImpl.java
Labels: :hammer: ci/cd, :+1: feat

#65 Users API 1차 개발 완료
  src/main/java/site/billbill/apiserver/api/users/controller/UserController.java
  src/main/java/site/billbill/apiserver/api/users/dto/response/ProfileResponse.java
  src/main/java/site/billbill/apiserver/api/users/dto/response/WishlistResponse.java
  src/main/java/site/billbill/apiserver/api/users/service/UserService.java
  src/main/java/site/billbill/apiserver/api/users/service/UserServiceImpl.java
  src/main/java/site/billbill/apiserver/repository/borrowPosts/ItemDslRepository.java
  src/main/java/site/billbill/apiserver/repository/borrowPosts/ItemDslRepositoryImpl.java
Labels: :hammer: ci/cd, :+1: feat

#66 Feature/borrow posts
  src/main/java/site/billbill/apiserver/api/borrowPosts/controller/PostsController.java
  src/main/java/site/billbill/apiserver/api/borrowPosts/converter/PostsConverter.java
  src/main/java/site/billbill/apiserver/api/borrowPosts/dto/request/PostsRequest.java
  src/main/java/site/billbill/apiserver/api/borrowPosts/service/PostsService.java
  src/main/java/site/billbill/apiserver/api/borrowPosts/service/PostsServiceImpl.java
  src/main/java/site/billbill/apiserver/model/post/ItemsCategoryJpaEntity.java
  src/main/java/site/billbill/apiserver/repository/borrowPosts/ItemsCategoryRepository.java
Labels: :hammer: ci/cd, :+1: feat
