Repository billbill-project/bill-api-server, pull requests merged in 2024-12, with the labels that each got.

#67 [feat] 채팅방 생성, 나가기, 상세정보 조회 api
  .github/workflows/dev_deply.yml
  src/main/java/site/billbill/apiserver/api/chat/controller/ChatController.java
  src/main/java/site/billbill/apiserver/api/chat/converter/ChatConverter.java
  src/main/java/site/billbill/apiserver/api/chat/dto/request/ChatRequest.java
  src/main/java/site/billbill/apiserver/api/chat/dto/response/ChatResponse.java
  src/main/java/site/billbill/apiserver/api/chat/service/ChatService.java
  src/main/java/site/billbill/apiserver/api/chat/service/ChatServiceImpl.java
  src/main/java/site/billbill/apiserver/api/chat/service/WebhookService.java
  src/main/java/site/billbill/apiserver/api/chat/service/WebhookServiceImpl.java
  src/main/java/site/billbill/apiserver/common/enums/chat/ChannelState.java
  src/main/java/site/billbill/apiserver/model/chat/ChatChannelJpaEntity.java
  src/main/java/site/billbill/apiserver/repository/borrowPosts/ItemsBorrowRepository.java
  src/main/java/site/billbill/apiserver/repository/chat/ChatRepository.java
Labels: :+1: feat

#68 [feat] 검색 api
  src/main/java/site/billbill/apiserver/api/borrowPosts/controller/PostsController.java
  src/main/java/site/billbill/apiserver/api/borrowPosts/converter/PostsConverter.java
  src/main/java/site/billbill/apiserver/api/borrowPosts/dto/response/PostsResponse.java
  src/main/java/site/billbill/apiserver/api/borrowPosts/service/PostsService.java
  src/main/java/site/billbill/apiserver/api/borrowPosts/service/PostsServiceImpl.java
  src/main/java/site/billbill/apiserver/repository/borrowPosts/ItemDslRepository.java
  src/main/java/site/billbill/apiserver/repository/borrowPosts/ItemDslRepositoryImpl.java
Labels: :hammer: ci/cd, :+1: feat

#69 Feature/borrow posts
  src/main/java/site/billbill/apiserver/api/borrowPosts/controller/PostsController.java
  src/main/java/site/billbill/apiserver/api/borrowPosts/converter/PostsConverter.java
  src/main/java/site/billbill/apiserver/api/borrowPosts/service/PostsService.java
  src/main/java/site/billbill/apiserver/api/borrowPosts/service/PostsServiceImpl.java
  src/main/java/site/billbill/apiserver/model/post/SearchKeywordStatsJpaEntity.java
  src/main/java/site/billbill/apiserver/model/user/UserSearchHistJpaEntity.java
  src/main/java/site/billbill/apiserver/repository/borrowPosts/SearchKeywordStatRepository.java
  src/main/java/site/billbill/apiserver/repository/user/UserSearchHistRepository.java
Labels: :hammer: ci/cd, :+1: feat

#72 [fix] JwtDto 수정
  src/main/java/site/billbill/apiserver/common/utils/jwt/JWTUtil.java
  src/main/java/site/billbill/apiserver/common/utils/jwt/dto/JwtDto.java
Labels: :hammer: ci/cd, :-1: fix

#73 [fix] 저장 검색어 주석 처리
  src/main/java/site/billbill/apiserver/api/borrowPosts/controller/PostsController.java
  src/main/java/site/billbill/apiserver/api/borrowPosts/service/PostsServiceImpl.java
Labels: :hammer: ci/cd, :-1: fix

#74 Feature/auth
  src/main/java/site/billbill/apiserver/api/auth/controller/AuthController.java
  src/main/java/site/billbill/apiserver/api/auth/dto/response/NicknameResponse.java
  src/main/java/site/billbill/apiserver/api/auth/service/AuthService.java
  src/main/java/site/billbill/apiserver/api/auth/service/AuthServiceImpl.java
  src/main/java/site/billbill/apiserver/api/users/controller/UserController.java
  src/main/java/site/billbill/apiserver/api/users/service/UserService.java
  src/main/java/site/billbill/apiserver/api/users/service/UserServiceImpl.java
  src/main/java/site/billbill/apiserver/repository/user/UserRepository.java
Labels: :hammer: ci/cd, :+1: feat

#75 [feat] 회원 프로필 API에 위치 정보 추가
  src/main/java/site/billbill/apiserver/api/users/dto/response/LocationResponse.java
  src/main/java/site/billbill/apiserver/api/users/dto/response/ProfileResponse.java
  src/main/java/site/billbill/apiserver/api/users/service/UserServiceImpl.java
Labels: :hammer: ci/cd, :+1: feat

#76 [fix] s3 swagger 수정 및 id 타입 변경
  src/main/java/site/billbill/apiserver/api/s3/Service/S3Service.java
  src/main/java/site/billbill/apiserver/api/s3/Service/S3ServiceImpl.java
  src/main/java/site/billbill/apiserver/api/s3/controller/S3Controller.java
  src/main/java/site/billbill/apiserver/api/s3/converter/S3Converter.java
  src/main/java/site/billbill/apiserver/api/s3/dto/response/S3Response.java
Labels: :hammer: ci/cd, :-1: fix

#77 API 추가/수정
  src/main/java/site/billbill/apiserver/api/auth/dto/request/LocationRequest.java
  src/main/java/site/billbill/apiserver/api/auth/service/AuthServiceImpl.java
  src/main/java/site/billbill/apiserver/api/users/controller/UserController.java
  src/main/java/site/billbill/apiserver/api/users/service/UserService.java
  src/main/java/site/billbill/apiserver/api/users/service/UserServiceImpl.java
  src/main/java/site/billbill/apiserver/model/BaseTime.java
Labels: :hammer: ci/cd, :+1: feat

#78 Feature/borrow posts
  src/main/java/site/billbill/apiserver/api/borrowPosts/controller/PostsController.java
  src/main/java/site/billbill/apiserver/api/borrowPosts/converter/PostsConverter.java
  src/main/java/site/billbill/apiserver/api/borrowPosts/dto/request/PostsRequest.java
  src/main/java/site/billbill/apiserver/api/borrowPosts/dto/response/PostsResponse.java
  src/main/java/site/billbill/apiserver/api/borrowPosts/service/PostsService.java
  src/main/java/site/billbill/apiserver/api/borrowPosts/service/PostsServiceImpl.java
  src/main/java/site/billbill/apiserver/repository/borrowPosts/BorrowHistRepository.java
  src/main/java/site/billbill/apiserver/repository/borrowPosts/ItemsReivewRepository.java
  src/main/java/site/billbill/apiserver/repository/chat/ChatRepository.java
Labels: :hammer: ci/cd, :+1: feat

#79 [feat] 거래처리
  src/main/java/site/billbill/apiserver/api/borrowPosts/controller/PostsController.java
  src/main/java/site/billbill/apiserver/api/borrowPosts/converter/PostsConverter.java
  src/main/java/site/billbill/apiserver/api/borrowPosts/dto/request/PostsRequest.java
  src/main/java/site/billbill/apiserver/api/borrowPosts/dto/response/PostsResponse.java
  src/main/java/site/billbill/apiserver/api/borrowPosts/service/PostsService.java
  src/main/java/site/billbill/apiserver/api/borrowPosts/service/PostsServiceImpl.java
  src/main/java/site/billbill/apiserver/model/post/BorrowHistJpaEntity.java
  src/main/java/site/billbill/apiserver/repository/borrowPosts/BorrowHistRepository.java
  src/main/java/site/billbill/apiserver/repository/borrowPosts/ItemDslRepositoryImpl.java
  src/main/java/site/billbill/apiserver/repository/borrowPosts/ItemsBorrowStatusRepository.java
Labels: :hammer: ci/cd, :+1: feat

#80 Feature/users 추가/수정
  src/main/java/site/billbill/apiserver/api/users/controller/UserController.java
  src/main/java/site/billbill/apiserver/api/users/dto/request/PasswordCheckRequest.java
  src/main/java/site/billbill/apiserver/api/users/dto/request/PasswordRequest.java
  src/main/java/site/billbill/apiserver/api/users/dto/response/BorrowHistoryResponse.java
  src/main/java/site/billbill/apiserver/api/users/dto/response/PostHistoryResponse.java
  src/main/java/site/billbill/apiserver/api/users/dto/response/ProfileResponse.java
  src/main/java/site/billbill/apiserver/api/users/service/UserService.java
  src/main/java/site/billbill/apiserver/api/users/service/UserServiceImpl.java
  src/main/java/site/billbill/apiserver/model/common/CodeDetailJpaEntity.java
  src/main/java/site/billbill/apiserver/model/common/embedded/CodeDetailId.java
  src/main/java/site/billbill/apiserver/model/post/embedded/ItemsLikeId.java
  src/main/java/site/billbill/apiserver/model/post/itemsLikeJpaEntity.java
  src/main/java/site/billbill/apiserver/model/user/UserJpaEntity.java
  src/main/java/site/billbill/apiserver/repository/borrowPosts/ItemDslRepositoryImpl.java
  src/main/java/site/billbill/apiserver/repository/common/CodeDetailRepository.java
Labels: :hammer: ci/cd, :+1: feat, :-1: fix

#82 [feat] 회원 탈퇴 API 탈퇴 코드 추가
  src/main/java/site/billbill/apiserver/api/users/controller/UserController.java
  src/main/java/site/billbill/apiserver/api/users/dto/request/WithdrawRequest.java
  src/main/java/site/billbill/apiserver/api/users/service/UserService.java
  src/main/java/site/billbill/apiserver/api/users/service/UserServiceImpl.java
  src/main/java/site/billbill/apiserver/model/user/WithdrawHistJpaEntity.java
  src/main/java/site/billbill/apiserver/repository/user/WithdrawHistRepository.java
Labels: :hammer: ci/cd, :+1: feat

#83 [feat] 리뷰조회
  src/main/java/site/billbill/apiserver/api/borrowPosts/controller/PostsController.java
  src/main/java/site/billbill/apiserver/api/borrowPosts/converter/PostsConverter.java
  src/main/java/site/billbill/apiserver/api/borrowPosts/dto/response/PostsResponse.java
  src/main/java/site/billbill/apiserver/api/borrowPosts/service/PostsService.java
  src/main/java/site/billbill/apiserver/api/borrowPosts/service/PostsServiceImpl.java
  src/main/java/site/billbill/apiserver/repository/borrowPosts/ItemsReivewRepository.java
Labels: :hammer: ci/cd, :+1: feat

#86 [temp] ci/cd용 임시 커밋
  src/main/java/site/billbill/apiserver/api/borrowPosts/service/PostsService.java
Labels: :hammer: ci/cd, :+1: feat, :-1: fix

#87 [temp] ci/cd 용 임시 커밋
  src/main/java/site/billbill/apiserver/repository/borrowPosts/ItemDslRepositoryImpl.java
Labels: :hammer: ci/cd

#88 [feat] 채팅목록 조회 구현
  src/main/java/site/billbill/apiserver/api/chat/controller/ChatController.java
  src/main/java/site/billbill/apiserver/api/chat/converter/ChatConverter.java
  src/main/java/site/billbill/apiserver/api/chat/dto/request/WebhookRequest.java
  src/main/java/site/billbill/apiserver/api/chat/dto/response/ChatResponse.java
  src/main/java/site/billbill/apiserver/api/chat/service/ChatService.java
  src/main/java/site/billbill/apiserver/api/chat/service/ChatServiceImpl.java
  src/main/java/site/billbill/apiserver/api/chat/service/WebhookService.java
  src/main/java/site/billbill/apiserver/api/chat/service/WebhookServiceImpl.java
  src/main/java/site/billbill/apiserver/common/enums/chat/ChannelState.java
  src/main/java/site/billbill/apiserver/repository/chat/ChatRepository.java
Labels: :+1: feat

#89 Feature/borrow posts
  src/main/java/site/billbill/apiserver/api/base/controller/BaseController.java
  src/main/java/site/billbill/apiserver/api/base/dto/request/ReportRequest.java
  src/main/java/site/billbill/apiserver/api/base/service/BaseService.java
  src/main/java/site/billbill/apiserver/api/base/service/BaseServiceImpl.java
  src/main/java/site/billbill/apiserver/api/borrowPosts/controller/PostsController.java
  src/main/java/site/billbill/apiserver/api/borrowPosts/service/PostsService.java
  src/main/java/site/billbill/apiserver/api/borrowPosts/service/PostsServiceImpl.java
  src/main/java/site/billbill/apiserver/api/users/service/UserServiceImpl.java
  src/main/java/site/billbill/apiserver/model/report/ReportHistJpaEntity.java
  src/main/java/site/billbill/apiserver/repository/borrowPosts/ItemDslRepository.java
  src/main/java/site/billbill/apiserver/repository/borrowPosts/ItemDslRepositoryImpl.java
  src/main/java/site/billbill/apiserver/repository/common/CodeDetailRepository.java
Labels: :hammer: ci/cd, :-1: fix

#90 API 추가/수정
  src/main/java/site/billbill/apiserver/api/borrowPosts/controller/PostsController.java
  src/main/java/site/billbill/apiserver/api/borrowPosts/dto/request/PostsRequest.java
  src/main/java/site/billbill/apiserver/api/borrowPosts/service/PostsService.java
  src/main/java/site/billbill/apiserver/api/borrowPosts/service/PostsServiceImpl.java
  src/main/java/site/billbill/apiserver/api/users/controller/UserController.java
  src/main/java/site/billbill/apiserver/api/users/dto/request/ProfileRequest.java
  src/main/java/site/billbill/apiserver/api/users/service/UserService.java
  src/main/java/site/billbill/apiserver/api/users/service/UserServiceImpl.java
  src/main/java/site/billbill/apiserver/repository/borrowPosts/ItemDslRepository.java
  src/main/java/site/billbill/apiserver/repository/borrowPosts/ItemDslRepositoryImpl.java
  src/main/java/site/billbill/apiserver/repository/user/UserDslRepository.java
  src/main/java/site/billbill/apiserver/repository/user/UserDslRepositoryImpl.java
Labels: :hammer: ci/cd, :+1: feat, :-1: fix

#91 회원가입, 로그인 로직 수정
  src/main/java/site/billbill/apiserver/api/auth/domain/UserBaseInfo.java
  src/main/java/site/billbill/apiserver/api/auth/dto/request/LoginRequest.java
  src/main/java/site/billbill/apiserver/api/auth/dto/request/SignupRequest.java
  src/main/java/site/billbill/apiserver/api/auth/service/AuthServiceImpl.java
  src/main/java/site/billbill/apiserver/model/user/UserJpaEntity.java
  src/main/java/site/billbill/apiserver/repository/user/UserDslRepository.java
  src/main/java/site/billbill/apiserver/repository/user/UserDslRepositoryImpl.java
  src/main/java/site/billbill/apiserver/repository/user/UserIdentityDslRepository.java
Labels: :hammer: ci/cd, :-1: fix

#92 [fix] toPost user 값 수정
  src/main/java/site/billbill/apiserver/api/borrowPosts/converter/PostsConverter.java
  src/main/java/site/billbill/apiserver/api/borrowPosts/service/PostsServiceImpl.java
Labels: :hammer: ci/cd, :-1: fix

#93 feat: 게시물 좋아요 취소 API
  src/main/java/site/billbill/apiserver/api/borrowPosts/controller/PostsController.java
  src/main/java/site/billbill/apiserver/api/borrowPosts/service/PostsService.java
  src/main/java/site/billbill/apiserver/api/borrowPosts/service/PostsServiceImpl.java
  src/main/java/site/billbill/apiserver/model/post/ItemsLikeJpaEntity.java
  src/main/java/site/billbill/apiserver/repository/borrowPosts/ItemDslRepositoryImpl.java
  src/main/java/site/billbill/apiserver/repository/borrowPosts/ItemsLikeRepository.java
Labels: :hammer: ci/cd, :+1: feat

#94 [fix] WebhookServiceImpl 생성자 수정
  src/main/java/site/billbill/apiserver/api/chat/service/WebhookServiceImpl.java
Labels: :-1: fix

#95 [fix] JsonFormat , null 방지 코드 추가
  src/main/java/site/billbill/apiserver/api/chat/dto/response/ChatResponse.java
  src/main/java/site/billbill/apiserver/api/chat/service/ChatServiceImpl.java
  src/main/java/site/billbill/apiserver/api/chat/service/WebhookServiceImpl.java
Labels: :-1: fix

#96 [feat] 대여날짜 수정 api 구현
  src/main/java/site/billbill/apiserver/api/chat/controller/ChatController.java
  src/main/java/site/billbill/apiserver/api/chat/dto/request/ChatRequest.java
  src/main/java/site/billbill/apiserver/api/chat/service/ChatService.java
  src/main/java/site/billbill/apiserver/api/chat/service/ChatServiceImpl.java
  src/main/java/site/billbill/apiserver/model/chat/ChatChannelJpaEntity.java
Labels: :+1: feat

#97 [refactor] 채팅 info 조회 response 값 추가
  src/main/java/site/billbill/apiserver/api/chat/converter/ChatConverter.java
  src/main/java/site/billbill/apiserver/api/chat/dto/response/ChatResponse.java
  src/main/java/site/billbill/apiserver/api/chat/service/ChatServiceImpl.java
Labels: ♻ refactor

#98 [refactor] 채팅 info 조회 response 값 추가
  src/main/java/site/billbill/apiserver/api/chat/converter/ChatConverter.java
  src/main/java/site/billbill/apiserver/api/chat/dto/response/ChatResponse.java
Labels: ♻ refactor

#99 [feat] 거래 취소 및 거래 확정 로직 추가
  src/main/java/site/billbill/apiserver/api/borrowPosts/controller/PostsController.java
  src/main/java/site/billbill/apiserver/api/borrowPosts/converter/PostsConverter.java
  src/main/java/site/billbill/apiserver/api/borrowPosts/dto/request/PostsRequest.java
  src/main/java/site/billbill/apiserver/api/borrowPosts/service/PostsService.java
  src/main/java/site/billbill/apiserver/api/borrowPosts/service/PostsServiceImpl.java
  src/main/java/site/billbill/apiserver/repository/borrowPosts/BorrowHistRepository.java
Labels: :hammer: ci/cd, :+1: feat, :-1: fix

#100 [refactor] 채팅 목록 response 값 추가
  src/main/java/site/billbill/apiserver/api/chat/converter/ChatConverter.java
  src/main/java/site/billbill/apiserver/api/chat/dto/response/ChatResponse.java
  src/main/java/site/billbill/apiserver/api/chat/service/ChatServiceImpl.java
Labels: ♻ refactor

#101 이메일 인증 API 개발 및 일부 API 수정
  .github/workflows/dev_deply.yml
  src/main/java/site/billbill/apiserver/api/auth/controller/AuthController.java
  src/main/java/site/billbill/apiserver/api/auth/dto/request/MailRequest.java
  src/main/java/site/billbill/apiserver/api/auth/dto/request/SignupRequest.java
  src/main/java/site/billbill/apiserver/api/auth/service/AuthServiceImpl.java
  src/main/java/site/billbill/apiserver/api/auth/service/MailService.java
  src/main/java/site/billbill/apiserver/config/mail/MailConfig.java
Labels: :hammer: ci/cd, :+1: feat, :-1: fix

#102 [fix] 비밀번호 변경 로직 수정
  src/main/java/site/billbill/apiserver/api/users/dto/request/PasswordRequest.java
  src/main/java/site/billbill/apiserver/api/users/service/UserServiceImpl.java
Labels: :hammer: ci/cd, :-1: fix

#103 [feat] 타 회원 대여내역 조회 API
  src/main/java/site/billbill/apiserver/api/users/controller/UserController.java
  src/main/java/site/billbill/apiserver/api/users/service/UserService.java
  src/main/java/site/billbill/apiserver/api/users/service/UserServiceImpl.java
Labels: :hammer: ci/cd, :+1: feat

#104 [fix] 프로필 조회 API 수정
  src/main/java/site/billbill/apiserver/api/users/controller/UserController.java
  src/main/java/site/billbill/apiserver/api/users/dto/response/ProfileResponse.java
  src/main/java/site/billbill/apiserver/api/users/service/UserServiceImpl.java
Labels: :hammer: ci/cd, :-1: fix

#105 [feat] 이메일 중복검사 API 개발
  src/main/java/site/billbill/apiserver/api/auth/controller/AuthController.java
  src/main/java/site/billbill/apiserver/api/auth/dto/response/ValidResponse.java
  src/main/java/site/billbill/apiserver/api/auth/service/AuthService.java
  src/main/java/site/billbill/apiserver/api/auth/service/AuthServiceImpl.java
  src/main/java/site/billbill/apiserver/repository/user/UserRepository.java
Labels: :hammer: ci/cd, :+1: feat

#106 [feat] 카카오 로그인 API
  src/main/java/site/billbill/apiserver/api/auth/controller/AuthController.java
  src/main/java/site/billbill/apiserver/api/auth/service/OAuthService.java
  src/main/java/site/billbill/apiserver/api/auth/service/OAuthServiceImpl.java
Labels: :hammer: ci/cd, :+1: feat

#107 [fix] 게시물 상세조회시 좋아요 여부 반환
  src/main/java/site/billbill/apiserver/api/borrowPosts/converter/PostsConverter.java
  src/main/java/site/billbill/apiserver/api/borrowPosts/dto/response/PostsResponse.java
  src/main/java/site/billbill/apiserver/api/borrowPosts/service/PostsServiceImpl.java
  src/main/java/site/billbill/apiserver/repository/borrowPosts/ItemsLikeRepository.java
Labels: :hammer: ci/cd, :+1: feat

#108 [fix] 리뷰 기간 데이터 추가
  src/main/java/site/billbill/apiserver/api/borrowPosts/converter/PostsConverter.java
  src/main/java/site/billbill/apiserver/api/borrowPosts/dto/response/PostsResponse.java
  src/main/java/site/billbill/apiserver/api/borrowPosts/service/PostsServiceImpl.java
  src/main/java/site/billbill/apiserver/repository/borrowPosts/BorrowHistRepository.java
Labels: :hammer: ci/cd, :+1: feat

#109 [fix] 상세보기 카테고리 관련
  src/main/java/site/billbill/apiserver/api/borrowPosts/converter/PostsConverter.java
Labels: :hammer: ci/cd, :-1: fix

#110 [fix] 거리처리 수정
  src/main/java/site/billbill/apiserver/api/borrowPosts/service/PostsServiceImpl.java
Labels: :hammer: ci/cd, :-1: fix
