Repository billbill-project/bill-api-server, pull requests merged in 2025-01, with the labels that each got.

#111 [fix] 권한 추가 및 조건 추가
  src/main/java/site/billbill/apiserver/api/borrowPosts/service/PostsServiceImpl.java
  src/main/java/site/billbill/apiserver/repository/borrowPosts/ItemsLikeRepository.java
Labels: :hammer: ci/cd, :-1: fix

#112 [fix] 리뷰 정렬
  src/main/java/site/billbill/apiserver/api/borrowPosts/controller/PostsController.java
  src/main/java/site/billbill/apiserver/api/borrowPosts/service/PostsService.java
  src/main/java/site/billbill/apiserver/api/borrowPosts/service/PostsServiceImpl.java
  src/main/java/site/billbill/apiserver/repository/borrowPosts/BorrowHistRepository.java
  src/main/java/site/billbill/apiserver/repository/borrowPosts/ItemsReivewRepository.java
Labels: :hammer: ci/cd, :-1: fix

#113 [fix] 권한 수정
  src/main/java/site/billbill/apiserver/api/borrowPosts/service/PostsServiceImpl.java
Labels: :hammer: ci/cd, :-1: fix

#114 [fix] 거래 취소
  src/main/java/site/billbill/apiserver/api/borrowPosts/service/PostsServiceImpl.java
Labels: :hammer: ci/cd, :-1: fix

#115 Feature/push
  .github/workflows/dev_deply.yml
  .gitignore
  build.gradle
  src/main/java/site/billbill/apiserver/api/push/controller/PushController.java
  src/main/java/site/billbill/apiserver/api/push/dto/request/PushRequest.java
  src/main/java/site/billbill/apiserver/api/push/service/PushService.java
  src/main/java/site/billbill/apiserver/api/push/service/PushServiceImpl.java
  src/main/java/site/billbill/apiserver/common/utils/jwt/JWTUtil.java
  src/main/java/site/billbill/apiserver/config/interceptor/BillApiInterceptor.java
  src/main/java/site/billbill/apiserver/external/firebase/fcm/dto/FcmMessageDto.java
  src/main/java/site/billbill/apiserver/external/firebase/fcm/utils/FirebaseUtil.java
Labels: :hammer: ci/cd, :+1: feat

#116 [fix] 오타 수정
  .github/workflows/dev_deply.yml
Labels: :hammer: ci/cd, :-1: fix

#118 [ci/cd]
  src/main/java/site/billbill/apiserver/api/sample/controller/SampleController.java
Labels: :hammer: ci/cd, :-1: fix

#119 [fix] 빌려준 기록 조회 API 수정
  src/main/java/site/billbill/apiserver/repository/borrowPosts/ItemDslRepositoryImpl.java
Labels: :hammer: ci/cd, :-1: fix

#120 [fix] 거리값 받게
  src/main/java/site/billbill/apiserver/api/borrowPosts/controller/PostsController.java
  src/main/java/site/billbill/apiserver/api/borrowPosts/converter/PostsConverter.java
  src/main/java/site/billbill/apiserver/api/borrowPosts/dto/request/PostsRequest.java
  src/main/java/site/billbill/apiserver/api/borrowPosts/service/PostsService.java
  src/main/java/site/billbill/apiserver/api/borrowPosts/service/PostsServiceImpl.java
  src/main/java/site/billbill/apiserver/model/post/ItemsJpaEntity.java
  src/main/java/site/billbill/apiserver/model/post/ItemsLocationJpaEntity.java
  src/main/java/site/billbill/apiserver/repository/borrowPosts/ItemDslRepositoryImpl.java
Labels: :hammer: ci/cd, :-1: fix

#121 [fix] 거래 수락 시점 수정
  src/main/java/site/billbill/apiserver/api/borrowPosts/converter/PostsConverter.java
  src/main/java/site/billbill/apiserver/api/borrowPosts/service/PostsServiceImpl.java
Labels: :hammer: ci/cd, :-1: fix

#122 [fix] 카카오 로그인 API Response 수정
  src/main/java/site/billbill/apiserver/api/auth/controller/AuthController.java
  src/main/java/site/billbill/apiserver/api/auth/dto/response/OAuthLoginResponse.java
  src/main/java/site/billbill/apiserver/api/auth/service/OAuthService.java
  src/main/java/site/billbill/apiserver/api/auth/service/OAuthServiceImpl.java
Labels: :hammer: ci/cd, :-1: fix

#124 [fix] 푸시 알림 저장 로직 추가
  src/main/java/site/billbill/apiserver/api/push/dto/request/PushRequest.java
  src/main/java/site/billbill/apiserver/api/push/service/PushServiceImpl.java
  src/main/java/site/billbill/apiserver/common/enums/alarm/PushType.java
  src/main/java/site/billbill/apiserver/model/alarm/AlarmListJpaEntity.java
  src/main/java/site/billbill/apiserver/model/alarm/AlarmLogJpaEntity.java
  src/main/java/site/billbill/apiserver/repository/alarm/AlarmListRepository.java
  src/main/java/site/billbill/apiserver/repository/alarm/AlarmLogRepository.java
  src/main/java/site/billbill/apiserver/repository/user/UserRepository.java
Labels: :hammer: ci/cd, :+1: feat

#127 [fix] 알람 로그 저장 로직 수정
  src/main/java/site/billbill/apiserver/api/push/service/PushServiceImpl.java
Labels: :hammer: ci/cd, :-1: fix

#128 [feat] 알림 리스트 조회
  src/main/java/site/billbill/apiserver/api/push/controller/PushController.java
  src/main/java/site/billbill/apiserver/api/push/converter/PushConverter.java
  src/main/java/site/billbill/apiserver/api/push/dto/response/PushResponse.java
  src/main/java/site/billbill/apiserver/api/push/service/PushService.java
  src/main/java/site/billbill/apiserver/api/push/service/PushServiceImpl.java
  src/main/java/site/billbill/apiserver/model/alarm/AlarmLogJpaEntity.java
  src/main/java/site/billbill/apiserver/repository/alarm/AlarmLogRepository.java
  src/main/java/site/billbill/apiserver/repository/chat/ChatRepository.java
Labels: :+1: feat

#129 [ci] 수정
  src/main/java/site/billbill/apiserver/api/push/controller/PushController.java
Labels: :hammer: ci/cd, :-1: fix

#130 [feat] 리뷰 알림 TaskScheduler 적용
  src/main/java/site/billbill/apiserver/api/borrowPosts/dto/response/PostsResponse.java
  src/main/java/site/billbill/apiserver/api/borrowPosts/service/PostsService.java
  src/main/java/site/billbill/apiserver/api/borrowPosts/service/PostsServiceImpl.java
  src/main/java/site/billbill/apiserver/common/enums/alarm/PushType.java
  src/main/java/site/billbill/apiserver/config/scheduler/TaskSchedulerConfig.java
  src/main/java/site/billbill/apiserver/repository/borrowPosts/BorrowHistRepository.java
  src/main/java/site/billbill/apiserver/repository/borrowPosts/ItemDslRepository.java
  src/main/java/site/billbill/apiserver/repository/borrowPosts/ItemDslRepositoryImpl.java
  src/main/java/site/billbill/apiserver/scheduler/TaskScheduler/Manager/ReviewNotificationManager.java
Labels: :hammer: ci/cd, :+1: feat

#131 [feat] 리뷰 알림 요청 스케줄링 구현
  src/main/java/site/billbill/apiserver/api/borrowPosts/service/PostsServiceImpl.java
  src/main/java/site/billbill/apiserver/external/firebase/fcm/utils/FirebaseUtil.java
  src/main/java/site/billbill/apiserver/model/post/ReviewAlertJpaEntity.java
  src/main/java/site/billbill/apiserver/repository/borrowPosts/ReviewAlertRepository.java
  src/main/java/site/billbill/apiserver/scheduler/TaskScheduler/Manager/ReviewNotificationManager.java
Labels: :hammer: ci/cd, :+1: feat

#132 [feat] 리뷰 체크 API
  src/main/java/site/billbill/apiserver/api/borrowPosts/converter/PostsConverter.java
  src/main/java/site/billbill/apiserver/api/borrowPosts/dto/response/PostsResponse.java
  src/main/java/site/billbill/apiserver/api/borrowPosts/service/PostsServiceImpl.java
  src/main/java/site/billbill/apiserver/api/push/controller/PushController.java
  src/main/java/site/billbill/apiserver/api/push/converter/PushConverter.java
  src/main/java/site/billbill/apiserver/api/push/dto/response/PushResponse.java
  src/main/java/site/billbill/apiserver/api/push/service/PushService.java
  src/main/java/site/billbill/apiserver/api/push/service/PushServiceImpl.java
  src/main/java/site/billbill/apiserver/repository/alarm/AlarmListRepository.java
  src/main/java/site/billbill/apiserver/repository/alarm/AlarmLogRepository.java
  src/main/java/site/billbill/apiserver/repository/borrowPosts/ItemsLocationRepository.java
  src/main/java/site/billbill/apiserver/repository/borrowPosts/ReviewAlertRepository.java
  src/main/java/site/billbill/apiserver/scheduler/TaskScheduler/Manager/ReviewNotificationManager.java
Labels: :hammer: ci/cd, :+1: feat, :-1: fix

#133 [feat] FcmMessageDto 수정
  src/main/java/site/billbill/apiserver/external/firebase/fcm/dto/FcmMessageDto.java
  src/main/java/site/billbill/apiserver/external/firebase/fcm/utils/FirebaseUtil.java
Labels: :hammer: ci/cd, :+1: feat

#134 [fix]리뷰 알림 수정
  src/main/java/site/billbill/apiserver/api/borrowPosts/service/PostsService.java
  src/main/java/site/billbill/apiserver/api/borrowPosts/service/PostsServiceImpl.java
  src/main/java/site/billbill/apiserver/api/push/service/PushServiceImpl.java
  src/main/java/site/billbill/apiserver/common/enums/alarm/PushType.java
  src/main/java/site/billbill/apiserver/scheduler/TaskScheduler/Manager/ReviewNotificationManager.java
Labels: :hammer: ci/cd, :-1: fix

#135 [fix] 알림목록 조회 REVIEW_ALERT pushType 제거
  src/main/java/site/billbill/apiserver/api/push/service/PushServiceImpl.java
  src/main/java/site/billbill/apiserver/repository/alarm/AlarmLogRepository.java
Labels: :-1: fix

#137 [fix] build ERROR 조치
  src/main/java/site/billbill/apiserver/api/borrowPosts/controller/PostsController.java
  src/main/java/site/billbill/apiserver/api/borrowPosts/service/PostsServiceImpl.java
  src/main/java/site/billbill/apiserver/repository/borrowPosts/ItemDslRepositoryImpl.java
Labels: :hammer: ci/cd, :-1: fix

#138 [fix] 상세정보 데이터 추가
  src/main/java/site/billbill/apiserver/api/borrowPosts/converter/PostsConverter.java
  src/main/java/site/billbill/apiserver/api/borrowPosts/dto/response/PostsResponse.java
  src/main/java/site/billbill/apiserver/config/scheduler/TaskSchedulerConfig.java
  src/main/java/site/billbill/apiserver/scheduler/TaskScheduler/Manager/ReviewNotificationManager.java
Labels: :hammer: ci/cd, :-1: fix

#141 [fix] 수정
  src/main/java/site/billbill/apiserver/repository/borrowPosts/BorrowHistRepository.java
  src/main/java/site/billbill/apiserver/repository/borrowPosts/ItemDslRepositoryImpl.java
Labels: :hammer: ci/cd, :-1: fix

#144 [fix] 수정
  src/main/java/site/billbill/apiserver/api/borrowPosts/controller/PostsController.java
  src/main/java/site/billbill/apiserver/api/borrowPosts/service/PostsServiceImpl.java
  src/main/java/site/billbill/apiserver/repository/borrowPosts/ItemDslRepositoryImpl.java
Labels: :hammer: ci/cd, :-1: fix

#145 [feat] 동의항목/알림 수신 여부 수정 API
  src/main/java/site/billbill/apiserver/api/users/controller/UserController.java
  src/main/java/site/billbill/apiserver/api/users/dto/request/AgreeRequest.java
  src/main/java/site/billbill/apiserver/api/users/service/UserService.java
  src/main/java/site/billbill/apiserver/api/users/service/UserServiceImpl.java
Labels: :hammer: ci/cd, :+1: feat

#146 [feat] 반납 요청알림구현 및 모듈화
  src/main/java/site/billbill/apiserver/api/borrowPosts/service/PostsServiceImpl.java
  src/main/java/site/billbill/apiserver/common/enums/alarm/PushType.java
  src/main/java/site/billbill/apiserver/model/post/ReviewAlertJpaEntity.java
  src/main/java/site/billbill/apiserver/repository/borrowPosts/ReviewAlertRepository.java
  src/main/java/site/billbill/apiserver/scheduler/TaskScheduler/Manager/ReviewNotificationManager.java
  src/main/java/site/billbill/apiserver/scheduler/TaskScheduler/Manager/TaskSchedulerManager.java
Labels: :hammer: ci/cd, :+1: feat

#147 [feat] 안 읽은 메세지 수 api
  .github/workflows/dev_deply.yml
  src/main/java/site/billbill/apiserver/api/chat/controller/ChatController.java
  src/main/java/site/billbill/apiserver/api/chat/converter/ChatConverter.java
  src/main/java/site/billbill/apiserver/api/chat/dto/request/ChatServerRequest.java
  src/main/java/site/billbill/apiserver/api/chat/dto/response/ChatResponse.java
  src/main/java/site/billbill/apiserver/api/chat/service/ChatServerService.java
  src/main/java/site/billbill/apiserver/api/chat/service/ChatServerServiceImpl.java
  src/main/java/site/billbill/apiserver/api/chat/service/ChatService.java
  src/main/java/site/billbill/apiserver/api/chat/service/ChatServiceImpl.java
  src/main/java/site/billbill/apiserver/api/chat/service/WebhookService.java
Labels: :+1: feat, ♻ refactor

#148 [fix] http method 수정
  src/main/java/site/billbill/apiserver/api/chat/controller/ChatController.java
Labels: :-1: fix

#149 [refactor] chatList payload 값 추가
  src/main/java/site/billbill/apiserver/api/chat/service/ChatServerService.java
  src/main/java/site/billbill/apiserver/api/chat/service/ChatServerServiceImpl.java
  src/main/java/site/billbill/apiserver/api/chat/service/ChatServiceImpl.java
Labels: ♻ refactor

#150 [refactor] ChatServerRequest에 notification 추가
  src/main/java/site/billbill/apiserver/api/chat/dto/request/ChatServerRequest.java
Labels: ♻ refactor

#151 [fix] ChatResponse, ChatConverter에 notification 추가
  src/main/java/site/billbill/apiserver/api/chat/converter/ChatConverter.java
  src/main/java/site/billbill/apiserver/api/chat/dto/response/ChatResponse.java
Labels: :-1: fix

#152 [feat] 채팅 알림 api
  src/main/java/site/billbill/apiserver/api/push/controller/PushController.java
  src/main/java/site/billbill/apiserver/api/push/dto/request/PushRequest.java
  src/main/java/site/billbill/apiserver/api/push/service/PushService.java
  src/main/java/site/billbill/apiserver/api/push/service/PushServiceImpl.java
  src/main/java/site/billbill/apiserver/config/interceptor/BillApiInterceptor.java
  src/main/java/site/billbill/apiserver/external/firebase/fcm/utils/FirebaseUtil.java
Labels: :+1: feat

#154 [fix] PushRequest -> PushRequest.SendPushRequest 수정
  src/main/java/site/billbill/apiserver/api/borrowPosts/service/PostsServiceImpl.java
  src/main/java/site/billbill/apiserver/api/push/service/PushService.java
  src/main/java/site/billbill/apiserver/api/push/service/PushServiceImpl.java
  src/main/java/site/billbill/apiserver/scheduler/TaskScheduler/Manager/TaskSchedulerManager.java
Labels: :-1: fix
